POST http://localhost:3000/post HTTP/1.1
content-type: application/json

{
    "title": "my post 2",
    "content": "geeting guy"
}

###
GET http://localhost:3000/posts HTTP/1.1
content-type: application/json

{
    "title": "my post",
    "content": "geeting guy"
}